---
#- name: Install, configure, and start Docker 
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
 
  - name: Install packages to allow apt to use a repository over HTTPS
    yum: 
      name:
        - yum-utils
        - device-mapper-persistent-data 
        - lvm2  
      state: present 
      update_cache: yes
   
  - name: Add Docker repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
  
  - name: Install docker
    yum: 
      name:
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
      state: present 
      update_cache: yes
  
  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
       
  - name: Add user jenkins to user group
    user:
      name: jenkins 
      groups: docker
      append: yes
  
  - name: Add user jenkins to user group
    user:
      name: ivaifua 
      groups: docker
      append: yes
  
  - name: Install pip
    easy_install:
      name: pip
      state: latest
    
  - python_requirements_info:
    
    
  - name: install docker-py
    pip: 
      name: docker-py
      state: latest
  
  - name: Remove  docker swarm
    docker_swarm:
        force: yes
        state: absent
  
  - name: Initializing docker swarm
    docker_swarm:
       state: present

  - name: Update swarm configuration
    docker_swarm:
       state: present
       election_tick: 5
         
  - name: Get info on Docker Swarm
    docker_swarm_info:
    ignore_errors: yes
    register: result
          
  - name: docker_swarm | Capturing Docker Swarm Worker join-token
    command: "docker swarm join-token -q manager"
    changed_when: false
    register: "docker_swarm_manager_token"

  - name: docker_swarm | Capturing Docker Swarm Networks
    command: "docker network ls"
    changed_when: false
    register: "docker_networks"

  - name: Create a swarm network
    docker_network:
       name: microservicesnetwork
       driver: overlay
       state: present 
       attachable: yes
