---
#- name: Install, configure, and start Docker 
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
           
  - name: Install packages to allow apt to use a repository over HTTPS
    yum: 
      name:
        - yum-utils
        - device-mapper-persistent-data 
        - lvm2 
        - python-pip
      state: present 
      update_cache: yes
   
  - name: Add Docker repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
  
  - name: Install docker
    yum: 
      name:
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
      state: present 
      update_cache: yes
    
  - name: Installing EPEL Repo (RedHat)
    yum:
      name: "epel-release"
      state: "present"
    when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"

  - name: Install Docker Module for Python
    pip:
        name: docker    
    
  - name: Install the 'Development tools' package group
    yum:
        name: "@Development tools"
        state: present  
        
  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
       
  - name: Add user jenkins to user group
    user:
      name: jenkins 
      groups: docker
      append: yes

