---
 - name: Create cartsdb container and connect to network
    docker_container:
      name: cartsdb
      image: mongo:latest
      state: started
      networks:
        - name: microservicesnetwork
      volumes:
        - cartsdb_volume:/data/db
