---
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: eu.gcr.io
      username: IvannaTetletska	
      debug: true
      password: " {{ lookup('file', '/var/lib/jenkins/workspace/Terraform/credentials.json')}} " 
  
  - name: Create a network
    docker_network:
      name: microservicesnetwork
  
  - name: Stop a container
    docker_container:
      name: carts
      state: stopped
      
  - name: remove container
    docker_container:
      name: carts
      state: absent
   
  - name: Create carts container
    docker_container:
      name: carts
      image: eu.gcr.io/silicon-dialect-245108/carts:latest
      networks:
       - name: microservicesnetwork

# - name: Create cartsdb container
#   docker_container:
 #    name: carts
#     image: eu.gcr.io/silicon-dialect-245108/cartsdb:latest
#     networks:
#      - name: microservicesnetwork
#     volumes:
 #      - cartsdb:/data/db
