---
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: eu.gcr.io
      username: _json_key	
      debug: true
      password: " {{ lookup('file', '/var/lib/jenkins/workspace/Terraform/credentials.json')}}" 
    
  - name: Create carts container
    docker_container:
      name: carts
      state: started
      image: eu.gcr.io/silicon-dialect-245108/carts:latest
      published_ports:
       - 8081
      networks:
       - name: microservicesnetwork
      purge_networks: yes
    register: register_carts_created  
    
  
      
  

  
