---
    - name: docker_swarm | Joining Docker Swarm Workers To Cluster
      docker_swarm:
         state: join
         advertise_addr: 10.10.0.3
         join_token: '{{hostvars[groups["webservers"][0]].docker_swarm_worker_token.stdout}}'   
         remote_addrs: [ '10.10.0.2:2377' ]
         
   
