---
  - name: Create a network
    docker_network:
      name: microservicesnetwork
      driver: overlay
      
  - name: Init a new swarm with default parameters
    docker_swarm:
      state: present    
